# Generated by Django 3.1.7 on 2021-03-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField()),
                ('api', models.CharField(help_text='API URL', max_length=512)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'drf_api_logs',
            },
        ),
    ]
