# Generated by Django 3.1.5 on 2021-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='api',
            field=models.CharField(help_text='API URL', max_length=1024),
        ),
    ]
