# Generated by Django 5.2.5 on 2026-02-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILogsModel',
        ),
    ]
